# Generated by Django 4.2 on 2024-02-01 16:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Teams",
            new_name="Team",
        ),
    ]
